# Generated by Django 5.2.3 on 2025-06-24 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_afiliacion_pago_usuario_delete_afiliado_pago_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='numero_celular',
            field=models.CharField(default='0000000000', max_length=20),
        ),
    ]
